# Spring boot application
server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/test
  datasource:
    url: jdbc:mysql://localhost:3309/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: password


